### ISSUE TITLE
bug in test_vic_time.py file

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#501]
when running `run_tests.py` for unit tests for the classic driver, there is an error in `test_vic_time` (should be an error in the classic and image drivers since it's a shared test). Specifically, the error is: 

```

dmy_feb_3_noon = <cdata 'dmy_struct *' owning 16 bytes>, dmy_june31 = <cdata 'dmy_struct *' owning 16 bytes>, dmy_too_many_seconds = <cdata 'dmy_struct *' owning 16 bytes>

    def test_invalid_date(dmy_feb_3_noon, dmy_june31, dmy_too_many_seconds):
        for cal in calendars:
>           assert vic_lib.invalid_date(calendars[cal], dmy_feb_3_noon) == 0
E           AttributeError: cffi library '//anaconda/envs/vic_test_env/lib/python3.5/site-packages/vic-5.0.0.dev_a87d259-py3.5-macosx-10.5-x86_64.egg/vic/../vic_core.cpython-35m-darwin.so' has no function, constant or global variable named 'invalid_date'

```

**Comment by jhamman** [comment]
I'm pretty sure this was fixed in e17b8d8553a1b1a3b8b92160f9a29852b47d4835.  Can you check to make sure you're testing against the current develop branch?

**Comment by dgergel** [comment]
I just pulled recent changes and am still seeing the error. This is when running `run_tests.py` as ```python run_tests.py  unit  --driver classic --output_dir $OUTPUT_DIR --data_dir $DATA_DIR --vic_exe /Users/diana/Dropbox/UW/VIC/vic/drivers/classic/vic_classic.exe```

**Comment by jhamman** [comment]
@dgergel  - have you:
1) rebuilt the classic driver?
2) rebuilt the python driver (`python setup.py install`)?

**Comment by dgergel** [comment]
@jhamman I had not rebuilt the python driver. This must have been the issue (although i don't really understand why, since I was testing the classic driver). Not seeing the error now.
